#+TITLE: elpm
/A elisp package manager with a cli/

* About
I want to be able to install packages and use them without being married to any particular emacs framework (like doom, spacemacs or my own config). Anyway, this package uses =straight.el= to do the actual heavy lifting of managing the packages. This package adds a package file, =elpm-packages.el=, a CLI for installing packages (=elpm=) and the ability to load packages (relatively easily) into any emacs instance -- in doom, spacemacs & even in =emacs -Q=. It is worth noting that the installation of packages is asynchronous and all usage of straight is sandboxed in a separate emacs subprocess.

* Quick start
** Setup
1. Clone this repo to your favorite location
    #+begin_src bash
git clone https://github.com/tylerware/elpm
    #+end_src
2. Add the repository to your elisp load path
   - By environment variable:
     #+begin_src bash
export EMACSLOADPATH="${EMACSLOADPATH}:/path/to/elmp"
     #+end_src
   - By elisp:
     #+begin_src elisp
(add-to-list 'load-path "/path/to/elmp")
     #+end_src
   - By creating a symlink to the file to your system's =site-lisp= directory
3. Add =./bin= to your systems =PATH= environment variable
     #+begin_src bash
export PATH="${PATH}:/path/to/elmp/bin"
     #+end_src

** Basic usage
Example installing / using packages installed in the =/tmp= directory
1. Install some packages
   - via CLI
     #+begin_src bash
cd /tmp
elpm evil \
    '(el-patch :type git :host github :repo "raxod502/el-patch")' # supports straight recipes
     #+end_src
   - via elisp
      #+begin_src elisp
(require 'elpm)
(elpm-use-packages
   '(evil
     (el-patch :type git :host github :repo "raxod502/el-patch"))
    "/tmp")
      #+end_src
2. Use the packages installed in =/tmp=
   #+begin_src elisp
(require 'elpm)
(elpm-use-all "/tmp")
(require 'evil)
(evil-mode)
   #+end_src
   You can use the packages you installed in any emacs instance.

* The CLI
This is the =elpm= cli definition -- just a convenient wrapper around the =elpm= package.
#+begin_src elisp :comments both :tangle bin/elpm :shebang #!/usr/bin/env -S emacs -Q --script # -*- mode: emacs-lisp; lexical-binding: t; -*-
(require 'elpm
         (concat (file-name-directory
                  (file-truename load-file-name))
                 "../elpm.el"))

(defun read-recipes (argv)
  (mapcar
   #'(lambda (arg) (car (read-from-string arg)))
   argv))

(elpm-use-packages
 (read-recipes argv)
 default-directory
 t)
#+end_src
* Package file
The =elpm-packages.el= file records what packages have been installed. Here is an example of what one looks like:
#+begin_src elisp
(:version 0
 :recipes
 (evil
  (el-patch :type git :host github :repo "raxod502/el-patch")))
#+end_src
Installing a package with =(elpm-use-package ...)= or =elpm= will add to the =:recipes= section of the file. It's worth noting that any packages that are listed in =:recipes= that aren't installed will be installed during the next running of =elpm= or =(elpm-use-all)=.
